#pragma config(Sensor, S1,     lightSensorL,   sensorEV3_Color, modeEV3Color_Ambient)
#pragma config(Sensor, S2,     ultraSensorL,   sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     ultraSensorR,   sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
// Calibrate light level
	int i = 0;
  float ambientLight = 0;
	while (i<5000)
	{
		float lightlevel = getColorAmbient( lightSensorL );
		motor[motorA] = 100;
		ambientLight = ((ambientLight*i)+lightlevel)/(i+1);
		i = i + 1;
		displayBigTextLine( 5, "Ambient Lvl: %d", ambientLight );
	}*/

float ambientLight = 10;
// Start
	while (true)
	{
		/***************************************************
										Light Sensor
		****************************************************/
		// level of light detected
		float lightlevel = getColorAmbient( lightSensorL );
		float leftMotor = 100;

		// algorithm for right motor
		float z = lightlevel-ambientLight;
		float rightMotor = 90*1/(1+exp(-(z/(ambientLight/3))));

		/***************************************************
										Ultrasonic Sensor
		****************************************************/
		float leftSense = getUSDistance(S2);
		float rightSense = getUSDistance(S3);
		/*
		if (leftSense < 10) {
			motor[motorD] = -rightMotor;
		}
		if (rightSense < 10) {
			motor[motorA] = -leftMotor;
		}


		motor[motorA] = leftMotor;
		motor[motorD] = rightMotor;
		*/
		if (leftSense < 20 && rightSense < 20){
			motor[motorA] = -20;
			motor[motorD] = -20;
			delay(1000);
		}else if (leftSense < 10) {
			motor[motorA] = -30;
			motor[motorD] = -60;
			delay(1000);
		}else if (rightSense < 10) {
			motor[motorA] = -60;
			motor[motorD] = -30;
			delay(1000);
		}else{
			motor[motorA] = leftMotor;
			motor[motorD] = rightMotor;
		}

		//motor[motorA] = (leftSense < 20)?-leftMotor : leftMotor;
		//motor[motorD] = (rightSense < 20)? -rightMotor : rightMotor;

		displayBigTextLine( 1, "Left: %d", leftMotor );
		displayBigTextLine( 3, "Right: %d", rightMotor );
		displayBigTextLine( 5, "Light Lvl: %d", lightlevel );
		displayBigTextLine( 7, "Ambient Lvl: %d", ambientLight );
		displayBigTextLine( 9, "LeftSense: %d", leftSense );
		displayBigTextLine( 11, "RightSense: %d", rightSense );
	}
}
