#pragma config(Sensor, S1,     lightSensorL,   sensorEV3_Color, modeEV3Color_Ambient)
#pragma config(Sensor, S4,     lightSensorR,   sensorEV3_Color, modeEV3Color_Ambient)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Set up bot with one light sensor front and center.
task main()
{
	//int i = 0;					//used to determine avg speed
	//float avgRPM = 0;		//used to determine avg speed

// Calibrate light level
	int i = 0;
  float ambientLight = 0;
	while (i<5000)
	{
		float lightlevel = getColorAmbient( lightSensorL );
		motor[motorA] = 100;
		ambientLight = ((ambientLight*i)+lightlevel)/(i+1);
		i = i + 1;
		displayBigTextLine( 5, "Ambient Lvl: %d", ambientLight );
	}


// Start
	while (true)
	{
			// level of light detected
		float lightlevel = getColorAmbient( lightSensorL );

//		float leftMotor = (centerAmbient - 10 ) + centerAmbient * 9;
//		float rightMotor = (centerAmbient - 10 ) + centerAmbient * 10;
			//float leftMotor = 100;
			//float rightMotor = 100 * (1/(1+exp(centerAmbient));

		float leftMotor = 100;

		float z = lightlevel-10;
		// algorithm for right motor
		float rightMotor = 90*1/(1+exp(-(z/20)));

		motor[motorA] = leftMotor;
		motor[motorD] = rightMotor;

		// determine average speed
		//float RPM = getMotorRPM(motorA);				//used to determine avg speed
		//float avgRPM = (avgRPM*i+RPM)/(i+1);		//used to determine avg speed
		//i += 1;																	//used to determine avg speed

		displayBigTextLine( 1, "Left: %d", leftMotor );
		displayBigTextLine( 3, "Right: %d", rightMotor );
		displayBigTextLine( 5, "Light Lvl: %d", lightlevel );
		displayBigTextLine( 7, "Ambient Lvl: %d", ambientLight );
		//displayBigTextLine( 7, "MotorA RPM: %d", RPM );					//used to determine avg speed
		//displayBigTextLine( 9, "avg RPM: %d", avgRPM );					//used to determine avg speed
		i += 1;
	}
}
